import { MigrationInterface, QueryRunner } from "typeorm";

export class CheckSchemaDiff1751301821213 implements MigrationInterface {
    name = 'CheckSchemaDiff1751301821213'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "courses" DROP CONSTRAINT "FK_26bcf0b4249de4f1f6fe662cb18"`);
        await queryRunner.query(`CREATE TYPE "public"."articles_mapping_tag_type_enum" AS ENUM('college_id', 'course_id', 'exam_id', 'course_group_id')`);
        await queryRunner.query(`CREATE TABLE "articles_mapping" ("articles_mapping_id" SERIAL NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "tag_type" "public"."articles_mapping_tag_type_enum" NOT NULL, "tag_type_id" integer NOT NULL, "article_id" integer, CONSTRAINT "PK_0d5107d9b2c15080349bc81ad49" PRIMARY KEY ("articles_mapping_id"))`);
        await queryRunner.query(`CREATE TABLE "college_exam_mapping" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "college_id" integer, "exam_id" integer, "course_group_id" integer, CONSTRAINT "PK_604cb962328cb45d4baf1254c38" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "templatization_college_content" ("templatization_id" SERIAL NOT NULL, "college_id" integer NOT NULL, "silos" character varying(50) NOT NULL, "description" text NOT NULL, "is_active" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_65e7424351ac2d521ef97a9c71a" PRIMARY KEY ("templatization_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_85b14d10136b5f048a30b1ecb1" ON "templatization_college_content" ("silos", "college_id") `);
        await queryRunner.query(`CREATE TYPE "public"."exam_question_papers_type_enum" AS ENUM('Question Paper', 'Sample Paper', 'Syllabus', 'Answer Key', 'General')`);
        await queryRunner.query(`CREATE TYPE "public"."exam_question_papers_subject_enum" AS ENUM('Physics', 'Chemistry', 'Maths', 'Biology', 'English', 'General Knowledge', 'Other')`);
        await queryRunner.query(`CREATE TYPE "public"."exam_question_papers_shift_enum" AS ENUM('Shift 1', 'Shift 2', 'Shift 3', 'Shift 4')`);
        await queryRunner.query(`CREATE TABLE "exam_question_papers" ("question_paper_id" SERIAL NOT NULL, "exam_id" integer NOT NULL, "title" character varying, "type" "public"."exam_question_papers_type_enum" NOT NULL, "year" integer, "subject" "public"."exam_question_papers_subject_enum", "shift" "public"."exam_question_papers_shift_enum", "file_url" character varying NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_b2966dba3ddbc82ff02e4eaaf88" PRIMARY KEY ("question_paper_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_90ec81a4cd39c4c19a555310df" ON "exam_question_papers" ("exam_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_1f0c5f9feeadea8c4231793562" ON "exam_question_papers" ("year") `);
        await queryRunner.query(`CREATE TABLE "course_group_content" ("course_group_content_id" SERIAL NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "title" character varying(300) NOT NULL, "description" text, "author_id" integer, "is_active" boolean NOT NULL DEFAULT false, "refrence_url" character varying(500), "meta_desc" character varying, "seo_param" text, "og_title" character varying, "og_description" character varying, "og_featured_img" character varying, "course_group_id" integer, "college_id" integer, CONSTRAINT "PK_8d9582ba8c0b888df84b0e28a2c" PRIMARY KEY ("course_group_content_id"))`);
        await queryRunner.query(`CREATE TYPE "public"."brochure_mapping_course_type_enum" AS ENUM('course_id', 'course_group_id')`);
        await queryRunner.query(`CREATE TABLE "brochure_mapping" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "course_type" "public"."brochure_mapping_course_type_enum" NOT NULL, "course_type_id" integer NOT NULL, "brochure_id" integer, CONSTRAINT "PK_492df3862512c89a361e26f15c5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "college_brochure" ("brochure_id" SERIAL NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "brochure_title" character varying NOT NULL, "brochure_file" character varying NOT NULL, "year" integer NOT NULL, "college_id" integer, CONSTRAINT "PK_accc088bb8dc44ed38e2634fdb9" PRIMARY KEY ("brochure_id"))`);
        await queryRunner.query(`CREATE TABLE "course_content" ("course_content_id" SERIAL NOT NULL, "course_id" integer, "silos" character varying(50), "is_active" boolean NOT NULL DEFAULT false, "title" character varying(300) NOT NULL, "description" text, "meta_desc" character varying, "author_id" integer, "refrence_url" character varying(500), "img1_url" character varying, "seo_param" text, "og_title" character varying, "og_description" character varying, "og_featured_img" character varying, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_2e924b0731cd61edc2393c7b0cb" PRIMARY KEY ("course_content_id"))`);
        await queryRunner.query(`ALTER TABLE "exam_date" DROP COLUMN "is_active"`);
        await queryRunner.query(`ALTER TABLE "exam_date" DROP COLUMN "tentative"`);
        await queryRunner.query(`ALTER TABLE "exam_date" DROP COLUMN "event_Title"`);
        await queryRunner.query(`ALTER TABLE "exam_date" DROP CONSTRAINT "UQ_79053ab9d80577f97a4a96859df"`);
        await queryRunner.query(`ALTER TABLE "exam_date" DROP COLUMN "slug"`);
        await queryRunner.query(`ALTER TABLE "exam_date" DROP COLUMN "exam_date"`);
        await queryRunner.query(`ALTER TABLE "exam_date" DROP COLUMN "refrence_url"`);
        await queryRunner.query(`ALTER TABLE "article" ADD "og_title" character varying`);
        await queryRunner.query(`ALTER TABLE "article" ADD "og_description" character varying`);
        await queryRunner.query(`ALTER TABLE "article" ADD "og_featured_img" character varying`);
        await queryRunner.query(`ALTER TABLE "exam_content" ADD "og_title" character varying`);
        await queryRunner.query(`ALTER TABLE "exam_content" ADD "og_description" character varying`);
        await queryRunner.query(`ALTER TABLE "exam_content" ADD "og_featured_img" character varying`);
        await queryRunner.query(`ALTER TABLE "exam_date" ADD "title" character varying(500)`);
        await queryRunner.query(`CREATE TYPE "public"."exam_date_event_type_enum" AS ENUM('Registration', 'Exam Date', 'Results', 'Cutoff', 'Counselling', 'Answer Key', 'Notification', 'Admit Card', 'Application', 'Miscellaneous')`);
        await queryRunner.query(`ALTER TABLE "exam_date" ADD "event_type" "public"."exam_date_event_type_enum"`);
        await queryRunner.query(`ALTER TABLE "exam_date" ADD "is_tentative" boolean`);
        await queryRunner.query(`ALTER TABLE "college_wise_fees" ADD "tution_fees" integer`);
        await queryRunner.query(`ALTER TABLE "college_wise_fees" ADD "hostel_fees" integer`);
        await queryRunner.query(`ALTER TABLE "college_wise_fees" ADD "admission_fees" integer`);
        await queryRunner.query(`ALTER TABLE "college_wise_fees" ADD "exam_fees" integer`);
        await queryRunner.query(`CREATE TYPE "public"."college_wise_fees_category_enum" AS ENUM('General', 'Sc', 'St', 'Obc', 'Nri')`);
        await queryRunner.query(`ALTER TABLE "college_wise_fees" ADD "category" "public"."college_wise_fees_category_enum"`);
        await queryRunner.query(`CREATE TYPE "public"."college_wise_fees_type_enum" AS ENUM('Year', 'Semester', 'Trimester', 'Quarter', 'Total')`);
        await queryRunner.query(`ALTER TABLE "college_wise_fees" ADD "type" "public"."college_wise_fees_type_enum"`);
        await queryRunner.query(`CREATE TYPE "public"."exam_exam_category_enum" AS ENUM('Study Abroad', 'Entrance', 'Govt Exam', 'Board')`);
        await queryRunner.query(`ALTER TABLE "exam" ADD "exam_category" "public"."exam_exam_category_enum"`);
        await queryRunner.query(`CREATE TYPE "public"."exam_exam_sub_category_enum" AS ENUM('Banking', 'Calendar', 'Defence', 'Alerts', 'PSU Recruitment', 'Railways', 'SSC', 'Teaching', 'UPSC', 'State PSC', 'Nursing', 'Scholarship', 'Police', 'Insurance')`);
        await queryRunner.query(`ALTER TABLE "exam" ADD "exam_sub_category" "public"."exam_exam_sub_category_enum"`);
        await queryRunner.query(`ALTER TABLE "exam" ADD "parent_exam_id" integer`);
        await queryRunner.query(`CREATE TYPE "public"."exam_exam_recognize_enum" AS ENUM('National', 'State')`);
        await queryRunner.query(`ALTER TABLE "exam" ADD "exam_recognize" "public"."exam_exam_recognize_enum"`);
        await queryRunner.query(`ALTER TABLE "exam" ADD "exam_recognize_state" character varying`);
        await queryRunner.query(`ALTER TABLE "exam" ADD "category_wise_fees" json`);
        await queryRunner.query(`ALTER TABLE "exam" ADD "course_slug" json`);
        await queryRunner.query(`ALTER TABLE "exam" ADD "parent_cutoff_category" character varying`);
        await queryRunner.query(`ALTER TABLE "exam" ADD "year" integer`);
        await queryRunner.query(`ALTER TABLE "exam" ADD "frequency" character varying`);
        await queryRunner.query(`CREATE TYPE "public"."exam_exam_level_enum" AS ENUM('12th', 'UG', 'PG')`);
        await queryRunner.query(`ALTER TABLE "exam" ADD "exam_level" "public"."exam_exam_level_enum"`);
        await queryRunner.query(`ALTER TABLE "college_content" ADD "og_title" character varying`);
        await queryRunner.query(`ALTER TABLE "college_content" ADD "og_description" character varying`);
        await queryRunner.query(`ALTER TABLE "college_content" ADD "og_featured_img" character varying`);
        await queryRunner.query(`ALTER TABLE "college_info" ADD "area" character varying`);
        await queryRunner.query(`ALTER TABLE "college_wise_course" ADD "display_name" character varying(500)`);
        await queryRunner.query(`ALTER TABLE "college_wise_course" ADD "author_id" integer`);
        await queryRunner.query(`ALTER TABLE "college_wise_course" ADD "title" character varying(500)`);
        await queryRunner.query(`ALTER TABLE "college_wise_course" ADD "meta_desc" character varying(500)`);
        await queryRunner.query(`ALTER TABLE "college_wise_course" ADD "seo_params" character varying(500)`);
        await queryRunner.query(`ALTER TABLE "college_wise_course" ADD "is_discontinued" boolean`);
        await queryRunner.query(`ALTER TABLE "college_wise_course" ADD "average_salary" integer`);
        await queryRunner.query(`ALTER TABLE "college_wise_course" ADD "median_salary" integer`);
        await queryRunner.query(`ALTER TABLE "college_wise_course" ADD "highest_salary" integer`);
        await queryRunner.query(`ALTER TABLE "college_wise_course" ADD "top_recruiters" character varying(500)`);
        await queryRunner.query(`ALTER TABLE "courses" ADD "duration_value" integer`);
        await queryRunner.query(`CREATE TYPE "public"."courses_duration_type_enum" AS ENUM('Years', 'Months', 'Days', 'Weeks')`);
        await queryRunner.query(`ALTER TABLE "courses" ADD "duration_type" "public"."courses_duration_type_enum"`);
        await queryRunner.query(`CREATE TYPE "public"."courses_course_type_enum" AS ENUM('full-time', 'part-time', 'distance', 'online', 'executive', 'Other', 'Honours', 'Lateral Entry', 'Certificate', 'Degree', 'Diploma')`);
        await queryRunner.query(`ALTER TABLE "courses" ADD "course_type" "public"."courses_course_type_enum"`);
        await queryRunner.query(`CREATE TYPE "public"."courses_course_mode_enum" AS ENUM('Full-Time', 'Part-Time', 'Online')`);
        await queryRunner.query(`ALTER TABLE "courses" ADD "course_mode" "public"."courses_course_mode_enum"`);
        await queryRunner.query(`CREATE TYPE "public"."courses_course_level_enum" AS ENUM('Ug', 'Pg')`);
        await queryRunner.query(`ALTER TABLE "courses" ADD "course_level" "public"."courses_course_level_enum"`);
        await queryRunner.query(`ALTER TABLE "courses" ADD "stream_id" integer`);
        await queryRunner.query(`ALTER TABLE "exam_date" DROP COLUMN "start_date"`);
        await queryRunner.query(`ALTER TABLE "exam_date" ADD "start_date" date`);
        await queryRunner.query(`ALTER TABLE "exam_date" DROP COLUMN "end_date"`);
        await queryRunner.query(`ALTER TABLE "exam_date" ADD "end_date" date`);
        await queryRunner.query(`ALTER TABLE "exam_date" DROP COLUMN "year"`);
        await queryRunner.query(`ALTER TABLE "exam_date" ADD "year" integer NOT NULL`);
        await queryRunner.query(`ALTER TYPE "public"."course_group_type_enum" RENAME TO "course_group_type_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."course_group_type_enum" AS ENUM('full-time', 'part-time', 'distance', 'online', 'executive', 'Other', 'Honours', 'Lateral Entry', 'Certificate', 'Degree', 'Diploma')`);
        await queryRunner.query(`ALTER TABLE "course_group" ALTER COLUMN "type" TYPE "public"."course_group_type_enum" USING "type"::"text"::"public"."course_group_type_enum"`);
        await queryRunner.query(`DROP TYPE "public"."course_group_type_enum_old"`);
        await queryRunner.query(`ALTER TYPE "public"."logs_type_enum" RENAME TO "logs_type_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."logs_type_enum" AS ENUM('college', 'user', 'exam', 'article', 'course')`);
        await queryRunner.query(`ALTER TABLE "logs" ALTER COLUMN "type" TYPE "public"."logs_type_enum" USING "type"::"text"::"public"."logs_type_enum"`);
        await queryRunner.query(`DROP TYPE "public"."logs_type_enum_old"`);
        await queryRunner.query(`ALTER TABLE "exam_date" ADD CONSTRAINT "UQ_14f577b81999868322f54cd7d5f" UNIQUE ("exam_id", "event_type", "year")`);
        await queryRunner.query(`ALTER TABLE "articles_mapping" ADD CONSTRAINT "FK_3c2d786e1ab915ecea2a0b438ba" FOREIGN KEY ("article_id") REFERENCES "article"("article_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "college_wise_course" ADD CONSTRAINT "FK_7a0c594949d58b40b0ed3adf4dc" FOREIGN KEY ("author_id") REFERENCES "author"("author_id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "courses" ADD CONSTRAINT "FK_72832d6391b8d9a675c61196e20" FOREIGN KEY ("stream_id") REFERENCES "stream"("stream_id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "college_exam_mapping" ADD CONSTRAINT "FK_ac8687094c648ef30638c89aa2c" FOREIGN KEY ("college_id") REFERENCES "college_info"("college_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "college_exam_mapping" ADD CONSTRAINT "FK_c8595dfd7e9caf4d8be48a4c778" FOREIGN KEY ("exam_id") REFERENCES "exam"("exam_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "college_exam_mapping" ADD CONSTRAINT "FK_0e21ad9a26b1a82652d1e5c2f97" FOREIGN KEY ("course_group_id") REFERENCES "course_group"("course_group_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "templatization_college_content" ADD CONSTRAINT "FK_741a5a1d8f35a7ed8374361d665" FOREIGN KEY ("college_id") REFERENCES "college_info"("college_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "exam_question_papers" ADD CONSTRAINT "FK_90ec81a4cd39c4c19a555310df8" FOREIGN KEY ("exam_id") REFERENCES "exam"("exam_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "course_group_content" ADD CONSTRAINT "FK_406dfe8e8790573e702f755023a" FOREIGN KEY ("course_group_id") REFERENCES "course_group"("course_group_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "course_group_content" ADD CONSTRAINT "FK_3cc7583f40ab904e28096ce7237" FOREIGN KEY ("college_id") REFERENCES "college_info"("college_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "brochure_mapping" ADD CONSTRAINT "FK_30b4ee90c95d4518d730c7af7df" FOREIGN KEY ("brochure_id") REFERENCES "college_brochure"("brochure_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "college_brochure" ADD CONSTRAINT "FK_39e2f3002e991abdae2df7fb1e8" FOREIGN KEY ("college_id") REFERENCES "college_info"("college_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "course_content" ADD CONSTRAINT "FK_89178486243763c734fd3ea24c3" FOREIGN KEY ("course_id") REFERENCES "courses"("course_id") ON DELETE SET NULL ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "course_content" DROP CONSTRAINT "FK_89178486243763c734fd3ea24c3"`);
        await queryRunner.query(`ALTER TABLE "college_brochure" DROP CONSTRAINT "FK_39e2f3002e991abdae2df7fb1e8"`);
        await queryRunner.query(`ALTER TABLE "brochure_mapping" DROP CONSTRAINT "FK_30b4ee90c95d4518d730c7af7df"`);
        await queryRunner.query(`ALTER TABLE "course_group_content" DROP CONSTRAINT "FK_3cc7583f40ab904e28096ce7237"`);
        await queryRunner.query(`ALTER TABLE "course_group_content" DROP CONSTRAINT "FK_406dfe8e8790573e702f755023a"`);
        await queryRunner.query(`ALTER TABLE "exam_question_papers" DROP CONSTRAINT "FK_90ec81a4cd39c4c19a555310df8"`);
        await queryRunner.query(`ALTER TABLE "templatization_college_content" DROP CONSTRAINT "FK_741a5a1d8f35a7ed8374361d665"`);
        await queryRunner.query(`ALTER TABLE "college_exam_mapping" DROP CONSTRAINT "FK_0e21ad9a26b1a82652d1e5c2f97"`);
        await queryRunner.query(`ALTER TABLE "college_exam_mapping" DROP CONSTRAINT "FK_c8595dfd7e9caf4d8be48a4c778"`);
        await queryRunner.query(`ALTER TABLE "college_exam_mapping" DROP CONSTRAINT "FK_ac8687094c648ef30638c89aa2c"`);
        await queryRunner.query(`ALTER TABLE "courses" DROP CONSTRAINT "FK_72832d6391b8d9a675c61196e20"`);
        await queryRunner.query(`ALTER TABLE "college_wise_course" DROP CONSTRAINT "FK_7a0c594949d58b40b0ed3adf4dc"`);
        await queryRunner.query(`ALTER TABLE "articles_mapping" DROP CONSTRAINT "FK_3c2d786e1ab915ecea2a0b438ba"`);
        await queryRunner.query(`ALTER TABLE "exam_date" DROP CONSTRAINT "UQ_14f577b81999868322f54cd7d5f"`);
        await queryRunner.query(`CREATE TYPE "public"."logs_type_enum_old" AS ENUM('college', 'user', 'exam', 'article')`);
        await queryRunner.query(`ALTER TABLE "logs" ALTER COLUMN "type" TYPE "public"."logs_type_enum_old" USING "type"::"text"::"public"."logs_type_enum_old"`);
        await queryRunner.query(`DROP TYPE "public"."logs_type_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."logs_type_enum_old" RENAME TO "logs_type_enum"`);
        await queryRunner.query(`CREATE TYPE "public"."course_group_type_enum_old" AS ENUM('full-time', 'part-time', 'distance', 'online', 'executive', 'Other')`);
        await queryRunner.query(`ALTER TABLE "course_group" ALTER COLUMN "type" TYPE "public"."course_group_type_enum_old" USING "type"::"text"::"public"."course_group_type_enum_old"`);
        await queryRunner.query(`DROP TYPE "public"."course_group_type_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."course_group_type_enum_old" RENAME TO "course_group_type_enum"`);
        await queryRunner.query(`ALTER TABLE "exam_date" DROP COLUMN "year"`);
        await queryRunner.query(`ALTER TABLE "exam_date" ADD "year" smallint`);
        await queryRunner.query(`ALTER TABLE "exam_date" DROP COLUMN "end_date"`);
        await queryRunner.query(`ALTER TABLE "exam_date" ADD "end_date" character varying`);
        await queryRunner.query(`ALTER TABLE "exam_date" DROP COLUMN "start_date"`);
        await queryRunner.query(`ALTER TABLE "exam_date" ADD "start_date" character varying`);
        await queryRunner.query(`ALTER TABLE "courses" DROP COLUMN "stream_id"`);
        await queryRunner.query(`ALTER TABLE "courses" DROP COLUMN "course_level"`);
        await queryRunner.query(`DROP TYPE "public"."courses_course_level_enum"`);
        await queryRunner.query(`ALTER TABLE "courses" DROP COLUMN "course_mode"`);
        await queryRunner.query(`DROP TYPE "public"."courses_course_mode_enum"`);
        await queryRunner.query(`ALTER TABLE "courses" DROP COLUMN "course_type"`);
        await queryRunner.query(`DROP TYPE "public"."courses_course_type_enum"`);
        await queryRunner.query(`ALTER TABLE "courses" DROP COLUMN "duration_type"`);
        await queryRunner.query(`DROP TYPE "public"."courses_duration_type_enum"`);
        await queryRunner.query(`ALTER TABLE "courses" DROP COLUMN "duration_value"`);
        await queryRunner.query(`ALTER TABLE "college_wise_course" DROP COLUMN "top_recruiters"`);
        await queryRunner.query(`ALTER TABLE "college_wise_course" DROP COLUMN "highest_salary"`);
        await queryRunner.query(`ALTER TABLE "college_wise_course" DROP COLUMN "median_salary"`);
        await queryRunner.query(`ALTER TABLE "college_wise_course" DROP COLUMN "average_salary"`);
        await queryRunner.query(`ALTER TABLE "college_wise_course" DROP COLUMN "is_discontinued"`);
        await queryRunner.query(`ALTER TABLE "college_wise_course" DROP COLUMN "seo_params"`);
        await queryRunner.query(`ALTER TABLE "college_wise_course" DROP COLUMN "meta_desc"`);
        await queryRunner.query(`ALTER TABLE "college_wise_course" DROP COLUMN "title"`);
        await queryRunner.query(`ALTER TABLE "college_wise_course" DROP COLUMN "author_id"`);
        await queryRunner.query(`ALTER TABLE "college_wise_course" DROP COLUMN "display_name"`);
        await queryRunner.query(`ALTER TABLE "college_info" DROP COLUMN "area"`);
        await queryRunner.query(`ALTER TABLE "college_content" DROP COLUMN "og_featured_img"`);
        await queryRunner.query(`ALTER TABLE "college_content" DROP COLUMN "og_description"`);
        await queryRunner.query(`ALTER TABLE "college_content" DROP COLUMN "og_title"`);
        await queryRunner.query(`ALTER TABLE "exam" DROP COLUMN "exam_level"`);
        await queryRunner.query(`DROP TYPE "public"."exam_exam_level_enum"`);
        await queryRunner.query(`ALTER TABLE "exam" DROP COLUMN "frequency"`);
        await queryRunner.query(`ALTER TABLE "exam" DROP COLUMN "year"`);
        await queryRunner.query(`ALTER TABLE "exam" DROP COLUMN "parent_cutoff_category"`);
        await queryRunner.query(`ALTER TABLE "exam" DROP COLUMN "course_slug"`);
        await queryRunner.query(`ALTER TABLE "exam" DROP COLUMN "category_wise_fees"`);
        await queryRunner.query(`ALTER TABLE "exam" DROP COLUMN "exam_recognize_state"`);
        await queryRunner.query(`ALTER TABLE "exam" DROP COLUMN "exam_recognize"`);
        await queryRunner.query(`DROP TYPE "public"."exam_exam_recognize_enum"`);
        await queryRunner.query(`ALTER TABLE "exam" DROP COLUMN "parent_exam_id"`);
        await queryRunner.query(`ALTER TABLE "exam" DROP COLUMN "exam_sub_category"`);
        await queryRunner.query(`DROP TYPE "public"."exam_exam_sub_category_enum"`);
        await queryRunner.query(`ALTER TABLE "exam" DROP COLUMN "exam_category"`);
        await queryRunner.query(`DROP TYPE "public"."exam_exam_category_enum"`);
        await queryRunner.query(`ALTER TABLE "college_wise_fees" DROP COLUMN "type"`);
        await queryRunner.query(`DROP TYPE "public"."college_wise_fees_type_enum"`);
        await queryRunner.query(`ALTER TABLE "college_wise_fees" DROP COLUMN "category"`);
        await queryRunner.query(`DROP TYPE "public"."college_wise_fees_category_enum"`);
        await queryRunner.query(`ALTER TABLE "college_wise_fees" DROP COLUMN "exam_fees"`);
        await queryRunner.query(`ALTER TABLE "college_wise_fees" DROP COLUMN "admission_fees"`);
        await queryRunner.query(`ALTER TABLE "college_wise_fees" DROP COLUMN "hostel_fees"`);
        await queryRunner.query(`ALTER TABLE "college_wise_fees" DROP COLUMN "tution_fees"`);
        await queryRunner.query(`ALTER TABLE "exam_date" DROP COLUMN "is_tentative"`);
        await queryRunner.query(`ALTER TABLE "exam_date" DROP COLUMN "event_type"`);
        await queryRunner.query(`DROP TYPE "public"."exam_date_event_type_enum"`);
        await queryRunner.query(`ALTER TABLE "exam_date" DROP COLUMN "title"`);
        await queryRunner.query(`ALTER TABLE "exam_content" DROP COLUMN "og_featured_img"`);
        await queryRunner.query(`ALTER TABLE "exam_content" DROP COLUMN "og_description"`);
        await queryRunner.query(`ALTER TABLE "exam_content" DROP COLUMN "og_title"`);
        await queryRunner.query(`ALTER TABLE "article" DROP COLUMN "og_featured_img"`);
        await queryRunner.query(`ALTER TABLE "article" DROP COLUMN "og_description"`);
        await queryRunner.query(`ALTER TABLE "article" DROP COLUMN "og_title"`);
        await queryRunner.query(`ALTER TABLE "exam_date" ADD "refrence_url" character varying(500)`);
        await queryRunner.query(`ALTER TABLE "exam_date" ADD "exam_date" character varying`);
        await queryRunner.query(`ALTER TABLE "exam_date" ADD "slug" character varying(100)`);
        await queryRunner.query(`ALTER TABLE "exam_date" ADD CONSTRAINT "UQ_79053ab9d80577f97a4a96859df" UNIQUE ("slug")`);
        await queryRunner.query(`ALTER TABLE "exam_date" ADD "event_Title" character varying(500)`);
        await queryRunner.query(`ALTER TABLE "exam_date" ADD "tentative" boolean`);
        await queryRunner.query(`ALTER TABLE "exam_date" ADD "is_active" boolean DEFAULT true`);
        await queryRunner.query(`DROP TABLE "course_content"`);
        await queryRunner.query(`DROP TABLE "college_brochure"`);
        await queryRunner.query(`DROP TABLE "brochure_mapping"`);
        await queryRunner.query(`DROP TYPE "public"."brochure_mapping_course_type_enum"`);
        await queryRunner.query(`DROP TABLE "course_group_content"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1f0c5f9feeadea8c4231793562"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_90ec81a4cd39c4c19a555310df"`);
        await queryRunner.query(`DROP TABLE "exam_question_papers"`);
        await queryRunner.query(`DROP TYPE "public"."exam_question_papers_shift_enum"`);
        await queryRunner.query(`DROP TYPE "public"."exam_question_papers_subject_enum"`);
        await queryRunner.query(`DROP TYPE "public"."exam_question_papers_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_85b14d10136b5f048a30b1ecb1"`);
        await queryRunner.query(`DROP TABLE "templatization_college_content"`);
        await queryRunner.query(`DROP TABLE "college_exam_mapping"`);
        await queryRunner.query(`DROP TABLE "articles_mapping"`);
        await queryRunner.query(`DROP TYPE "public"."articles_mapping_tag_type_enum"`);
        await queryRunner.query(`ALTER TABLE "courses" ADD CONSTRAINT "FK_26bcf0b4249de4f1f6fe662cb18" FOREIGN KEY ("specialization_id") REFERENCES "specialization"("specialization_id") ON DELETE SET NULL ON UPDATE NO ACTION`);
    }

}
